version: '3'
services:
  db:
    image: docker.io/mariadb:10.6.12
    container_name: izpbx-db
    command: --sql-mode=ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    restart: unless-stopped
    env_file:
    - .env
    environment:
    - TZ
    - MYSQL_DATABASE
    - MYSQL_USER
    - MYSQL_PASSWORD
    - MYSQL_ROOT_PASSWORD
    #- MARIADB_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD}
    #- MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=${MYSQL_ALLOW_EMPTY_ROOT_PASSWORD}
    volumes:
    #- /etc/localtime:/etc/localtime:ro
    - ./data/db:/var/lib/mysql
    ports:
    - 3306:3306

  # https://hub.docker.com/r/izdock/izpbx-asterisk/tags?page=1&ordering=last_updated
  izpbx:
    image: docker.io/izdock/izpbx-asterisk:20.16.5
    container_name: izpbx
    restart: unless-stopped
    depends_on:
    - db
    env_file:
    - .env
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./data/izpbx:/data
    cap_add:
    - NET_ADMIN
    privileged: true
    ulimits:
      nofile:
        soft: 8192
        hard: 32768
    ports:
      - ${APP_PORT_HTTP}:${APP_PORT_HTTP}
      - ${APP_PORT_HTTPS}:${APP_PORT_HTTPS}
      - ${APP_PORT_IAX}:${APP_PORT_IAX}
      - ${APP_PORT_IAX}:${APP_PORT_IAX}/udp
      - ${APP_PORT_PJSIP}:${APP_PORT_PJSIP}
      - ${APP_PORT_PJSIP}:${APP_PORT_PJSIP}/udp
      - ${APP_PORT_SIP}:${APP_PORT_SIP}/udp
      - ${APP_PORT_SIP}:${APP_PORT_SIP}
      - ${APP_PORT_WEBRTC}:${APP_PORT_WEBRTC}
      - ${APP_PORT_UCP_HTTP}:${APP_PORT_UCP_HTTP}
      - ${APP_PORT_UCP_HTTPS}:${APP_PORT_UCP_HTTPS}
      - ${APP_PORT_AMI}:${APP_PORT_AMI}
      - ${APP_PORT_RTP_START}-${APP_PORT_RTP_END}:${APP_PORT_RTP_START}-${APP_PORT_RTP_END}
      - ${APP_PORT_RTP_START}-${APP_PORT_RTP_END}:${APP_PORT_RTP_START}-${APP_PORT_RTP_END}/udp
      - ${APP_PORT_DHCP}:${APP_PORT_DHCP}/udp
      - ${APP_PORT_TFTP}:${APP_PORT_TFTP}
      - ${APP_PORT_TFTP}:${APP_PORT_TFTP}/udp
      - ${APP_PORT_NTP}:${APP_PORT_NTP}/udp
      - ${APP_PORT_FOP2}:${APP_PORT_FOP2}
      - ${APP_PORT_ZABBIX}:${APP_PORT_ZABBIX}
